sudo: required

language : generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t ddak2ya/react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true ddak2ya/react_app npm run test

after_success:
  - echo "Test Success"
